### ISSUE TITLE
Problemas con la APP

### ISSUE THREAD

**Issue by laucpacheco** [Capigol/LUDe_v2#2]
Estoy intentando generar decoys para un set de ligandos que tengo, sin embargo, tengo problemas ya que abrí varias pestañas para cargar mis archivos y la aplicación se cayó. Me gustaría obtener información acerca de cuando se reestablece el servicio y recomendaciones sobre su uso, ya que no se si es adecuado cargar varios archivos al tiempo.

Muchas gracias, quedo atenta a su respuesta.

**Comment by Capigol** [comment]
Estimada Laura, gracias por notificarnos acerca del problema. 
Seguramente se quedó sin memoria y dejó de funcionar. Ya reinicié la app y está funcionando nuevamente. Sin embargo, el servidor está atravesando algunos problemas y está un poco más lento que lo habitual.

Esta app está cargada en el servidor de streamlit, que es gratuito, pero que tiene una memoria limitada (1GB), por lo que mi recomendación es que corras en una sola ventana y largues una nueva corrida una vez que finalizó. Además el numero de moléculas input tampoco debería ser muy grande porque también te quedarías sin memoria (50 máximo).

Si necesitas cargar más moléculas te puedo ofrecer 2 opciones:
- Que descargues el github completo de LUDe, instales el environment.yml en tu PC y corras streamlit en tu PC. Si necesitas ayuda te puedo asesorar.
- Que me envies los inputs, los corro en mi PC y te los reenvio los resultados.

Espero haber sido de ayuda.

Lucas

**Comment by laucpacheco** [comment]
Estimado Lucas,

muchas gracias por tu respuesta. Opté por la primera opción que me
brindaste, en vista de que tengo 49717 moléculas.

Logré clonar tu repositorio, instalarlo en mi PC y hacerlo correr. Estoy
intentando con varias pestañas abiertas al tiempo (16) e ingresando de a 99
moléculas, ya que noté que la Appi tiene un límite de 100 moléculas por
corrida y por ahora está corriendo sin problema, aunque está un poco
demorado.

Nuevamente muchas gracias por responder y por trabajo con la app, es
maravilloso.

Saludos,

Laura.

**Comment by Capigol** [comment]
Hola Laura, me alegra que hayas podido hacer funcionar la app en tu PC.

49000 moléculas sería imposible correrlas todas juntas. Haces bien en spliterla en sets más chicos. Lo único malo es que estás perdiendo una característica de la app que es que al final compara todos los decoys con todos los activos y elimina los más parecidos estructuralmente. En tu caso solo serán comparadas las 99 moléculas de cada subset con sus respectivos decoys.

Gracias por tus comentarios!

Saludos, 

Lucas
